### ISSUE TITLE
Feat: Integrate Azure App insights SDK

### ISSUE THREAD

**Issue by jdhaines** [rropen/SFM#13]
**Topic**
Integrate the SDK for Azure App insights into the backend to allow not only traditional logging (Error, Debug, Info, Critical) but app insights notifications.  These can then be displayed in nice dashboards and also be acted on with events to send emails or text messages on certain events.

I think the SDK code is [here](https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure).  Nice Microsoft docs are [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python)

**Service**
Backend

**Steps**

**Comment by TylerB890** [comment]
Worked with Ian to confirm that python logs are being passed into Azure dashboard and can be queried by the App Insights Log within the dashboard.
