### ISSUE TITLE
Feat: Create first Vue component: dropdown sidebar

### ISSUE THREAD

**Issue by willcbelcher** [rropen/SFM#15]
**Topic**
A tracer issue for the first Vue component to be added to the application.  Need to create a sidebar with a dropdown menu for changing which metrics are being accessed (by repo, org, etc.). Also need to feed in fake JSON data that will eventually come from API. 

**Service**
Frontend

**Steps**
- [ ] Create sidebar Vue component
- [ ] Create fake JSON data and link to component
- [ ] sidebar loads in app 
- [ ] tests?

**Comment by jdhaines** [comment]
This will be separate from a drop down component, might want to edit the title.

**Comment by willcbelcher** [comment]
This has been added to VueCobalt.
