### ISSUE TITLE
Defect: Update Sidebar styling and format

### ISSUE THREAD

**Issue by willcbelcher** [rropen/SFM#30]
**Topic**
Currently the sidebar has some styling issues that need to be fixed, such as gray space on the side and too much padding on the right (not enough space for content). 

**Service**
Frontend

**Steps**
- [ ] Fix styling and formatting

**Comment by jdhaines** [comment]
Fixed the edge (grey) padding in 5740bf5f5931e9fa002a7e4ba0eda955c7ae9b8f

Not sure what you mean about too much "padding on the right".

Adding all the content, filters, dropdowns, etc. won't be part of an issue related to format and styling.  That will build as we built out associated features with charts and such.  Should probably remove that task on this issue.

Issues should be about a small and defined piece of work (feature, debt, risk, defect).  Styling would be either feature or defect.  Adding the sidebar content would usually be a feature.  I don't think debt is the right classification here.

**Comment by willcbelcher** [comment]
Aw bummer, i had already started on this. The padding on the right refers to the right of the sidebar. I think the area for the actual chart content is too small, too much whitespace in there. Just wanted to play around with it and see what it looked like with a bit more real estate.

I'll update the issue to reflect all those changes. I still think we need to adress thee content of the sidebar though, because currently it doesn't make a ton of sense. We don't need to provide the options for the dropdown, but shouldn't we add a placeholder in there? Right now the sidebar has like, "Report", "Team", etc.

**Comment by willcbelcher** [comment]
I created a pull request where i just updated the padding for the central content. If you don't think it looks better feel free to discard and close everything out.

**Comment by jdhaines** [comment]
I think I get your point, but that dotted line wasn't the actual content... that was just there from Tailwind.  That wasn't really the zone for our charts.

Also the placeholders in sidebar won't actually be links like that.  Those are also leftover from the component in tailwind.  I left them just to remind us of the styling that looks good.  There won't be traditional links there (probably).  I'm find with the changing of the dotted line box but that'll disappear once we have real content.
