### ISSUE TITLE
Debt: Add documentation for how all the metrics are calculated

### ISSUE THREAD

**Issue by willcbelcher** [rropen/SFM#38]
**Topic**
The way the official "Elite" vs "Medium", etc. standards are calculated is similar to how Google calculates them. These will need to be thoroughly documented in the "about" page so users know exactly how we determine our own metrics. 

**Service**
Both

**Steps**
- [ ] Add documentation to README.md
- [ ] Add documentation to about page

**Comment by jdhaines** [comment]
Checking in to see how this one is coming along?

**Comment by calvinmead1** [comment]
I have the information but I haven't added to the documentation. I have been focused on the class and helping William when he needs it. I plan on tackling the issues this week as tomorrow will be a week since I started to mainly focus on the class.

**Comment by willcbelcher** [comment]
This is the information that will go in the pop-up modals, correct? If so, we should wait to put it in until the modal gets pulled into VueCobalt. That way we can just pass in the info that Calvin made as props.
