### ISSUE TITLE
Debt: Strange Chart vs. Deployments Naming

### ISSUE THREAD

**Issue by jdhaines** [rropen/SFM#39]
**Topic**
Need to resolve the chart endpoints vs. deployments.  The `/charts` endpoint is called *Get Deployments* but you have to pass in a deployments string... let's clean this up.  Don't call it charts because we don't know how someone might want to use this data.  Deployments should just be another collection that you can GET from.

Someday we might want this to be GraphQL because I might want *deployements* or perhaps *Deployments -> Commits*

![image](https://user-images.githubusercontent.com/3834260/133889636-9ed9972e-7400-4c9b-9a74-457f1913f616.png)

![image](https://user-images.githubusercontent.com/3834260/133889653-55af0c37-22ea-4e42-b69a-b6822bf854a3.png)

**Service**
Backend

**Comment by TylerB890** [comment]
Commit 14468fd changed group_projects query parameter to "all_deployments" and added HTTPExceptions to query errors. Now returns a verbose error when project_id / project_name are both provided but do not match.
