### ISSUE TITLE
Debt: Refactor Home Page Script

### ISSUE THREAD

**Issue by jdhaines** [rropen/SFM#40]
**Topic**
Refactoring William's initial work on the `Home.vue` view.

**Service**
Frontend

**Steps**
- [x] Implement Environment Variables
- [x] Refactor Axios Requests
- [x] Simply logic (use computed, map, etc.)
- [x] Add type support
- [x] Clean up and remove commented (extra) code
- [x] Refactor dates for Apex Charts
- [x] Change tailwind to badge from box

**Comment by jdhaines** [comment]
@willcbelcher @TylerB890 @geiger96 @calvinmead1 @ITM007 

Good learning experience to take the Frontend code William wrote and systematically refactor it with a new section completed in the different commits in the connected PR.

**Comment by willcbelcher** [comment]
I think this is ready to be closed. Is this refactor done?

**Comment by jdhaines** [comment]
Complete.
