### ISSUE TITLE
Debt: Add additional info to lead time endpoint

### ISSUE THREAD

**Issue by willcbelcher** [rropen/SFM#49]
**Topic**
Lead time to change endpoint needs one change and one addition. See the steps and examples below. 

**Service**
Backend

**Steps**
- [ ] Add array of daily lead time to change (see example below). I will need an array of doubles, where each double is [unix date timestamp, lead time for that day]. Every day will need to be included. If it doesn't have data, then its probably fine to leave it out, but we will see what that looks like on the chart. 
- [ ] Change "performance" metric to be time based, e.g. "one week", "one day", etc. 
- [ ] Change endpoint keys to be camel case, e.g. leadTime vs. lead_time

Example endpoint:
```json
{
  "lead_time": 13680,
  "time_units": "minutes",
  "performance": "One Week",
  "lead_time_description": "median lead time for a commit to get pulled to main branch in minutes",
  "performance_description": "Elite = less than one day, High = between one day and one week, Medium = bewtween one week and one month, Low = greater than one month"
  "leadTimeDates": [
    [1627058415, 25]
    [1627144815 19]
    [1627231215, 0]
    [1627317615, 26]
    [1627404015, 50]
  ]
}
```

**Comment by TylerB890** [comment]
closed and passing tests via d081eaa
