### ISSUE TITLE
Feat: Create SFM-Specific Database Models

### ISSUE THREAD

**Issue by TylerB890** [rropen/SFM#7]
**Topic**
Creation of work_Item and project database models based on Josh's draw.io diagram. Built out in SqlModel with Pydantic models (built within SqlModel) like work_item_create, and work_item_read, which will help validate api requests and responses. 

**Service**
Backend

**Steps**
- [ ] Create initial work_item database model
- [ ] Create initial project database model
- [ ] Create Pydantic models for request and response validation

**Comment by jdhaines** [comment]
Although snake_case is standard in python for functions and variables, you should use camelCase for any data that will be shared through the API. 

Sites like [this one](https://restfulapi.net/resource-naming/) should help. That should include database table names, unless you all agree to another standard. I'm not bothered if you do, but pick one and let's stick with it.

**Comment by jdhaines** [comment]
Closed with #25
