### ISSUE TITLE
Defect: Fix flake8 change, and catch no Github_API_Key

### ISSUE THREAD

**Issue by TylerB890** [rropen/SFM#84]
**Topic**
ignore flake8 line and add a try_catch if user uses github populate without a github_api_key

**Service**
backend
**Steps**
- [ ] Step 1?

**Comment by TylerB890** [comment]
Add division by 0 on sfm change failure rate for SFM

**Comment by geiger96** [comment]
Last comment caused by william's operator error. Original issues are fixed.
